export {
  useGetAdminUsersQuery,
  useGetAdminUserQuery,
  useSetUserBannedMutation,
  useGetAdminSummaryQuery,
  useGetAdminDepositsQuery,
  useApproveDepositMutation,
  useRejectDepositMutation,
  useGetAdminProductsQuery,
  useSetProductPriceMutation,
  useSyncProductsMutation,
  useAdjustBalanceMutation,
  useGetAdminsQuery,
  useGrantAdminMutation,
  useRevokeAdminMutation,
  type AdminSummary,
  type AdminDepositRow,
  type AdminProductRow,
  type AdminRow,
  type AdminUserRow,
  type AdminUserDetail,
} from './api/adminApi';
