export {
  useGetDiscountsQuery,
  useCreateDiscountMutation,
  useSetDiscountActiveMutation,
  useDeleteDiscountMutation,
  useGetAdminUsersQuery,
  useGetAdminFeedbackQuery,
  useGetAdminUserQuery,
  useLazyGetAdminOrderItemsQuery,
  useSetUserBannedMutation,
  useGetAdminSummaryQuery,
  useGetMoneyAnalyticsQuery,
  useGetAdminDepositsQuery,
  useApproveDepositMutation,
  useRejectDepositMutation,
  useGetAdminProductsQuery,
  useSetProductPriceMutation,
  useAnnounceNewArrivalMutation,
  usePublishLowStockMutation,
  useSetProductAvailabilityMutation,
  useSetProductInstructionsMutation,
  useSetProductLogoMutation,
  useReorderProductsMutation,
  useResetProductOrderMutation,
  useSyncProductsMutation,
  useAdjustBalanceMutation,
  useGetAdminsQuery,
  useGrantAdminMutation,
  useRevokeAdminMutation,
  useGetAdminMaintenanceQuery,
  useSetAdminMaintenanceMutation,
  useSetAdminMaintenanceImageMutation,
  useGetBackupsQuery,
  useSetBackupIntervalMutation,
  useCreateBackupMutation,
  useDownloadBackupMutation,
  useRestoreStoredBackupMutation,
  useImportBackupMutation,
  type MaintenanceState,
  type AdminSummary,
  type AdminMoneyAnalytics,
  type AdminDepositRow,
  type AdminProductRow,
  type AdminRow,
  type AdminUserRow,
  type AdminFeedbackRow,
  type AdminFeedbackPage,
  type AdminUserDetail,
  type AdminDiscountRow,
  type BackupEntry,
  type BackupStatus,
} from './api/adminApi';
