export {
  useGetAdminSummaryQuery,
  useGetAdminDepositsQuery,
  useApproveDepositMutation,
  useRejectDepositMutation,
  useGetAdminProductsQuery,
  useSetProductPriceMutation,
  useSyncProductsMutation,
  useAdjustBalanceMutation,
  useGetAdminsQuery,
  useGrantAdminMutation,
  useRevokeAdminMutation,
  type AdminSummary,
  type AdminDepositRow,
  type AdminProductRow,
  type AdminRow,
} from './api/adminApi';
